# Generated by Django 3.1.4 on 2020-12-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_name',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_name',
            field=models.ManyToManyField(blank=True, null=True, to='store.Category'),
        ),
    ]
