# Generated by Django 3.1.4 on 2020-12-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201226_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_name',
            field=models.ManyToManyField(blank=True, to='store.SubCategory'),
        ),
    ]
