# Generated by Django 3.1.5 on 2021-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PICKED', 'PICKED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=155, null=True),
        ),
    ]
